language: node_js
node_js:
- 12
cache:
  directories:
  - node_modules
install:
- yarn
branches:
  only:
  - travis-test
script:
- yarn build
addons:
  ssh_known_hosts:
  - 47.112.48.225
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
after_success:
- scp -o StrictHostKeyChecking=no -r ./public $remote_user@$remote_ip:$project_dir
