language: node_js

# 指定 NodeJs 版本，也可直接设为 stable
node_js:
  - 12

# 缓存依赖
cache:
  directories:
    - node_modules

# 使用 yarn 安装
install:
  - yarn

# 设置需要监听的分支
branches:
  only:
    - master

# 需要执行的脚本
script:
  - yarn build

# 添加 SSH 信任列表（服务器的IP）
addons: $remote_ip

# 用于 ssh 连接服务器
before_install:
  - openssl aes-256-cbc -K $encrypted_1dc9eec206f9_key -iv $encrypted_1dc9eec206f9_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d

# 执行部署脚本 （$remote_ip $remote_user $project_dir 在 travis 上配置即可）
after_success:
  - ssh $remote_user@$remote_ip -o StrictHostKeyChecking=no rm -rf $project_dir
  - scp -o StrictHostKeyChecking=no -r ./docs/.vuepress/dist $remote_user@$remote_ip:$project_dir
